Repository matplotlib/mpl-brochure-site, pull requests merged in 2021-11, with the labels that each got.

#26 publish the html directory to gh-pages
  .github/workflows/main.yaml
Labels: maintenance

#19 ENH: add an image rotator to brochure page
  README.md
  docs/_static/css/landing.css
  docs/_static/images-rotate/_generate_images.py
  docs/_static/images-rotate/bar300.png
  docs/_static/images-rotate/barbs300.png
  docs/_static/images-rotate/boxplot_plot300.png
  docs/_static/images-rotate/contour300.png
  docs/_static/images-rotate/contourf300.png
  docs/_static/images-rotate/errorbar_plot300.png
  docs/_static/images-rotate/eventplot300.png
  docs/_static/images-rotate/fill_between300.png
  docs/_static/images-rotate/hexbin300.png
  docs/_static/images-rotate/hist2d300.png
  docs/_static/images-rotate/hist_plot300.png
  docs/_static/images-rotate/imshow300.png
  docs/_static/images-rotate/info.js
  docs/_static/images-rotate/pcolormesh300.png
  docs/_static/images-rotate/pie300.png
  docs/_static/images-rotate/plot300.png
  docs/_static/images-rotate/quiver300.png
  docs/_static/images-rotate/scatter_plot300.png
  docs/_static/images-rotate/stem300.png
  docs/_static/images-rotate/step300.png
  docs/_static/images-rotate/streamplot300.png
  docs/_static/images-rotate/violin300.png
  docs/_static/images/sphx_glr_3D_thumb.png
  docs/_static/images/sphx_glr_contour_thumb.png
  docs/_static/images/sphx_glr_histogram_thumb.png
  docs/_static/images/sphx_glr_membrane_thumb.png
  docs/_static/script.js
  docs/body.html
Labels: enhancement

#35 MNT: link fixes and copyedits...
  docs/_templates/landing_footer.html
  docs/body.html
Labels: maintenance

#38 DOC: link getting started in users doc
  docs/body.html
Labels: documentation
